#!/usr/bin/env bash

cp /autograder/submission/sol/exercise_1.cpp /autograder/source/test_data/exercise_1/exercise_1.cpp
cp /autograder/submission/sol/exercise_2.cpp /autograder/source/test_data/exercise_2/exercise_2.cpp
cp /autograder/submission/sol/exercise_3.cpp /autograder/source/test_data/exercise_3/exercise_3.cpp

cd /autograder/source

python3 run_tests.py

exit 0